[features]
seeds = false
[programs.devnet]
nft_breeding = "DjmjJdk6BK4JxLNUccicPbofcTCrNZU5avE4mnenPxxC"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "./Users/awaisahmed/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migration/initialize.ts"
compute = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migration/compute.ts"
mintChild = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migration/mintChild.ts"
updateUri = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migration/updateUri.ts"